// Code generated by golex. DO NOT EDIT.

package parser

import (
	"strconv"
	"strings"

	"modernc.org/golex/lex"
)

func (l *lexer) scan(lval *yySymType) lex.Char {
	c := l.Enter()

yystate0:
	yyrule := -1
	_ = yyrule
	c = l.Rule0()

	goto yystart1

	goto yystate0 // silence unused label error
	goto yyAction // silence unused label error
yyAction:
	switch yyrule {
	case 1:
		goto yyrule1
	case 2:
		goto yyrule2
	case 3:
		goto yyrule3
	case 4:
		goto yyrule4
	case 5:
		goto yyrule5
	case 6:
		goto yyrule6
	case 7:
		goto yyrule7
	case 8:
		goto yyrule8
	case 9:
		goto yyrule9
	case 10:
		goto yyrule10
	case 11:
		goto yyrule11
	case 12:
		goto yyrule12
	case 13:
		goto yyrule13
	case 14:
		goto yyrule14
	case 15:
		goto yyrule15
	case 16:
		goto yyrule16
	case 17:
		goto yyrule17
	case 18:
		goto yyrule18
	case 19:
		goto yyrule19
	case 20:
		goto yyrule20
	case 21:
		goto yyrule21
	case 22:
		goto yyrule22
	case 23:
		goto yyrule23
	case 24:
		goto yyrule24
	case 25:
		goto yyrule25
	case 26:
		goto yyrule26
	case 27:
		goto yyrule27
	case 28:
		goto yyrule28
	case 29:
		goto yyrule29
	case 30:
		goto yyrule30
	case 31:
		goto yyrule31
	case 32:
		goto yyrule32
	case 33:
		goto yyrule33
	case 34:
		goto yyrule34
	case 35:
		goto yyrule35
	case 36:
		goto yyrule36
	case 37:
		goto yyrule37
	case 38:
		goto yyrule38
	case 39:
		goto yyrule39
	case 40:
		goto yyrule40
	case 41:
		goto yyrule41
	case 42:
		goto yyrule42
	case 43:
		goto yyrule43
	case 44:
		goto yyrule44
	case 45:
		goto yyrule45
	case 46:
		goto yyrule46
	case 47:
		goto yyrule47
	case 48:
		goto yyrule48
	case 49:
		goto yyrule49
	case 50:
		goto yyrule50
	case 51:
		goto yyrule51
	case 52:
		goto yyrule52
	case 53:
		goto yyrule53
	case 54:
		goto yyrule54
	case 55:
		goto yyrule55
	case 56:
		goto yyrule56
	case 57:
		goto yyrule57
	case 58:
		goto yyrule58
	case 59:
		goto yyrule59
	case 60:
		goto yyrule60
	case 61:
		goto yyrule61
	case 62:
		goto yyrule62
	case 63:
		goto yyrule63
	case 64:
		goto yyrule64
	case 65:
		goto yyrule65
	case 66:
		goto yyrule66
	case 67:
		goto yyrule67
	case 68:
		goto yyrule68
	case 69:
		goto yyrule69
	case 70:
		goto yyrule70
	case 71:
		goto yyrule71
	case 72:
		goto yyrule72
	case 73:
		goto yyrule73
	}
	goto yystate1 // silence unused label error
yystate1:
	c = l.Next()
yystart1:
	switch {
	default:
		goto yyabort
	case c == '!':
		goto yystate6
	case c == '"':
		goto yystate9
	case c == '$':
		goto yystate12
	case c == '%':
		goto yystate14
	case c == '&':
		goto yystate18
	case c == '(':
		goto yystate20
	case c == ')':
		goto yystate22
	case c == '*':
		goto yystate23
	case c == '+':
		goto yystate28
	case c == ',':
		goto yystate32
	case c == '-':
		goto yystate34
	case c == '.':
		goto yystate38
	case c == '/':
		goto yystate40
	case c == '0':
		goto yystate49
	case c == ':':
		goto yystate55
	case c == ';':
		goto yystate56
	case c == '<':
		goto yystate57
	case c == '=':
		goto yystate63
	case c == '>':
		goto yystate66
	case c == '?':
		goto yystate72
	case c == '@':
		goto yystate73
	case c == '[':
		goto yystate81
	case c == '\n':
		goto yystate3
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate2
	case c == ']':
		goto yystate83
	case c == '^':
		goto yystate84
	case c == '`':
		goto yystate85
	case c == 'b':
		goto yystate87
	case c == 'c':
		goto yystate92
	case c == 'd':
		goto yystate107
	case c == 'e':
		goto yystate117
	case c == 'f':
		goto yystate123
	case c == 'i':
		goto yystate133
	case c == 'r':
		goto yystate136
	case c == 's':
		goto yystate144
	case c == 't':
		goto yystate150
	case c == 'v':
		goto yystate154
	case c == 'w':
		goto yystate157
	case c == '{':
		goto yystate162
	case c == '|':
		goto yystate164
	case c == '}':
		goto yystate166
	case c >= '1' && c <= '9':
		goto yystate52
	case c >= 'A' && c <= 'Z' || c == '_' || c == 'a' || c == 'g' || c == 'h' || c >= 'j' && c <= 'q' || c == 'u' || c >= 'x' && c <= 'z' || c == '\u0080':
		goto yystate78
	}

yystate2:
	c = l.Next()
	yyrule = 1
	l.Mark()
	switch {
	default:
		goto yyrule1
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate2
	}

yystate3:
	c = l.Next()
	yyrule = 10
	l.Mark()
	switch {
	default:
		goto yyrule10
	case c == ')':
		goto yystate5
	case c == '\t' || c == ' ':
		goto yystate4
	}

yystate4:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == ')':
		goto yystate5
	case c == '\t' || c == ' ':
		goto yystate4
	}

yystate5:
	c = l.Next()
	yyrule = 18
	l.Mark()
	goto yyrule18

yystate6:
	c = l.Next()
	yyrule = 40
	l.Mark()
	switch {
	default:
		goto yyrule40
	case c == '=':
		goto yystate7
	}

yystate7:
	c = l.Next()
	yyrule = 39
	l.Mark()
	switch {
	default:
		goto yyrule39
	case c == '\n':
		goto yystate8
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate7
	}

yystate8:
	c = l.Next()
	yyrule = 39
	l.Mark()
	goto yyrule39

yystate9:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate10
	case c == '\\':
		goto yystate11
	case c >= '\x01' && c <= '!' || c >= '#' && c <= '[' || c >= ']' && c <= 'ÿ':
		goto yystate9
	}

yystate10:
	c = l.Next()
	yyrule = 69
	l.Mark()
	goto yyrule69

yystate11:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'ÿ':
		goto yystate9
	}

yystate12:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080':
		goto yystate13
	}

yystate13:
	c = l.Next()
	yyrule = 68
	l.Mark()
	switch {
	default:
		goto yyrule68
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate13
	}

yystate14:
	c = l.Next()
	yyrule = 37
	l.Mark()
	switch {
	default:
		goto yyrule37
	case c == '=':
		goto yystate17
	case c == '\n':
		goto yystate16
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate15
	}

yystate15:
	c = l.Next()
	yyrule = 37
	l.Mark()
	switch {
	default:
		goto yyrule37
	case c == '\n':
		goto yystate16
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate15
	}

yystate16:
	c = l.Next()
	yyrule = 37
	l.Mark()
	goto yyrule37

yystate17:
	c = l.Next()
	yyrule = 8
	l.Mark()
	goto yyrule8

yystate18:
	c = l.Next()
	yyrule = 27
	l.Mark()
	switch {
	default:
		goto yyrule27
	case c == '&':
		goto yystate19
	}

yystate19:
	c = l.Next()
	yyrule = 25
	l.Mark()
	goto yyrule25

yystate20:
	c = l.Next()
	yyrule = 17
	l.Mark()
	switch {
	default:
		goto yyrule17
	case c == '\n':
		goto yystate21
	case c == '\t' || c == ' ':
		goto yystate20
	}

yystate21:
	c = l.Next()
	yyrule = 17
	l.Mark()
	goto yyrule17

yystate22:
	c = l.Next()
	yyrule = 19
	l.Mark()
	goto yyrule19

yystate23:
	c = l.Next()
	yyrule = 35
	l.Mark()
	switch {
	default:
		goto yyrule35
	case c == '*':
		goto yystate26
	case c == '=':
		goto yystate27
	case c == '\n':
		goto yystate25
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate24
	}

yystate24:
	c = l.Next()
	yyrule = 35
	l.Mark()
	switch {
	default:
		goto yyrule35
	case c == '\n':
		goto yystate25
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate24
	}

yystate25:
	c = l.Next()
	yyrule = 35
	l.Mark()
	goto yyrule35

yystate26:
	c = l.Next()
	yyrule = 32
	l.Mark()
	goto yyrule32

yystate27:
	c = l.Next()
	yyrule = 6
	l.Mark()
	goto yyrule6

yystate28:
	c = l.Next()
	yyrule = 33
	l.Mark()
	switch {
	default:
		goto yyrule33
	case c == '=':
		goto yystate31
	case c == '\n':
		goto yystate30
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate29
	}

yystate29:
	c = l.Next()
	yyrule = 33
	l.Mark()
	switch {
	default:
		goto yyrule33
	case c == '\n':
		goto yystate30
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate29
	}

yystate30:
	c = l.Next()
	yyrule = 33
	l.Mark()
	goto yyrule33

yystate31:
	c = l.Next()
	yyrule = 4
	l.Mark()
	goto yyrule4

yystate32:
	c = l.Next()
	yyrule = 12
	l.Mark()
	switch {
	default:
		goto yyrule12
	case c == '\n':
		goto yystate33
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate32
	}

yystate33:
	c = l.Next()
	yyrule = 12
	l.Mark()
	goto yyrule12

yystate34:
	c = l.Next()
	yyrule = 34
	l.Mark()
	switch {
	default:
		goto yyrule34
	case c == '=':
		goto yystate37
	case c == '\n':
		goto yystate36
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate35
	}

yystate35:
	c = l.Next()
	yyrule = 34
	l.Mark()
	switch {
	default:
		goto yyrule34
	case c == '\n':
		goto yystate36
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate35
	}

yystate36:
	c = l.Next()
	yyrule = 34
	l.Mark()
	goto yyrule34

yystate37:
	c = l.Next()
	yyrule = 5
	l.Mark()
	goto yyrule5

yystate38:
	c = l.Next()
	yyrule = 15
	l.Mark()
	switch {
	default:
		goto yyrule15
	case c == '.':
		goto yystate39
	}

yystate39:
	c = l.Next()
	yyrule = 14
	l.Mark()
	goto yyrule14

yystate40:
	c = l.Next()
	yyrule = 36
	l.Mark()
	switch {
	default:
		goto yyrule36
	case c == '*':
		goto yystate43
	case c == '/':
		goto yystate46
	case c == '=':
		goto yystate48
	case c == '\n':
		goto yystate42
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate41
	}

yystate41:
	c = l.Next()
	yyrule = 36
	l.Mark()
	switch {
	default:
		goto yyrule36
	case c == '\n':
		goto yystate42
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate41
	}

yystate42:
	c = l.Next()
	yyrule = 36
	l.Mark()
	goto yyrule36

yystate43:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == '*':
		goto yystate44
	case c >= '\x01' && c <= ')' || c >= '+' && c <= 'ÿ':
		goto yystate43
	}

yystate44:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == '*':
		goto yystate44
	case c == '/':
		goto yystate45
	case c >= '\x01' && c <= ')' || c >= '+' && c <= '.' || c >= '0' && c <= 'ÿ':
		goto yystate43
	}

yystate45:
	c = l.Next()
	yyrule = 2
	l.Mark()
	switch {
	default:
		goto yyrule2
	case c == '*':
		goto yystate44
	case c >= '\x01' && c <= ')' || c >= '+' && c <= 'ÿ':
		goto yystate43
	}

yystate46:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == '\n':
		goto yystate47
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'ÿ':
		goto yystate46
	}

yystate47:
	c = l.Next()
	yyrule = 3
	l.Mark()
	goto yyrule3

yystate48:
	c = l.Next()
	yyrule = 7
	l.Mark()
	goto yyrule7

yystate49:
	c = l.Next()
	yyrule = 66
	l.Mark()
	switch {
	default:
		goto yyrule66
	case c == '.':
		goto yystate50
	case c == 'X' || c == 'x':
		goto yystate53
	case c >= '0' && c <= '9':
		goto yystate52
	}

yystate50:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate51
	}

yystate51:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c >= '0' && c <= '9':
		goto yystate51
	}

yystate52:
	c = l.Next()
	yyrule = 66
	l.Mark()
	switch {
	default:
		goto yyrule66
	case c == '.':
		goto yystate50
	case c >= '0' && c <= '9':
		goto yystate52
	}

yystate53:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate54
	}

yystate54:
	c = l.Next()
	yyrule = 65
	l.Mark()
	switch {
	default:
		goto yyrule65
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate54
	}

yystate55:
	c = l.Next()
	yyrule = 13
	l.Mark()
	goto yyrule13

yystate56:
	c = l.Next()
	yyrule = 11
	l.Mark()
	goto yyrule11

yystate57:
	c = l.Next()
	yyrule = 43
	l.Mark()
	switch {
	default:
		goto yyrule43
	case c == '<':
		goto yystate60
	case c == '=':
		goto yystate61
	case c == '\n':
		goto yystate59
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate58
	}

yystate58:
	c = l.Next()
	yyrule = 43
	l.Mark()
	switch {
	default:
		goto yyrule43
	case c == '\n':
		goto yystate59
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate58
	}

yystate59:
	c = l.Next()
	yyrule = 43
	l.Mark()
	goto yyrule43

yystate60:
	c = l.Next()
	yyrule = 30
	l.Mark()
	goto yyrule30

yystate61:
	c = l.Next()
	yyrule = 41
	l.Mark()
	switch {
	default:
		goto yyrule41
	case c == '\n':
		goto yystate62
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate61
	}

yystate62:
	c = l.Next()
	yyrule = 41
	l.Mark()
	goto yyrule41

yystate63:
	c = l.Next()
	yyrule = 9
	l.Mark()
	switch {
	default:
		goto yyrule9
	case c == '=':
		goto yystate64
	}

yystate64:
	c = l.Next()
	yyrule = 38
	l.Mark()
	switch {
	default:
		goto yyrule38
	case c == '\n':
		goto yystate65
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate64
	}

yystate65:
	c = l.Next()
	yyrule = 38
	l.Mark()
	goto yyrule38

yystate66:
	c = l.Next()
	yyrule = 44
	l.Mark()
	switch {
	default:
		goto yyrule44
	case c == '=':
		goto yystate69
	case c == '>':
		goto yystate71
	case c == '\n':
		goto yystate68
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate67
	}

yystate67:
	c = l.Next()
	yyrule = 44
	l.Mark()
	switch {
	default:
		goto yyrule44
	case c == '\n':
		goto yystate68
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate67
	}

yystate68:
	c = l.Next()
	yyrule = 44
	l.Mark()
	goto yyrule44

yystate69:
	c = l.Next()
	yyrule = 42
	l.Mark()
	switch {
	default:
		goto yyrule42
	case c == '\n':
		goto yystate70
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate69
	}

yystate70:
	c = l.Next()
	yyrule = 42
	l.Mark()
	goto yyrule42

yystate71:
	c = l.Next()
	yyrule = 31
	l.Mark()
	goto yyrule31

yystate72:
	c = l.Next()
	yyrule = 16
	l.Mark()
	goto yyrule16

yystate73:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == '{':
		goto yystate76
	case c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080':
		goto yystate74
	}

yystate74:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == '(':
		goto yystate75
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate74
	}

yystate75:
	c = l.Next()
	yyrule = 72
	l.Mark()
	goto yyrule72

yystate76:
	c = l.Next()
	yyrule = 20
	l.Mark()
	switch {
	default:
		goto yyrule20
	case c == '\n':
		goto yystate77
	case c == '\t' || c == ' ':
		goto yystate76
	}

yystate77:
	c = l.Next()
	yyrule = 20
	l.Mark()
	goto yyrule20

yystate78:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate79:
	c = l.Next()
	yyrule = 71
	l.Mark()
	goto yyrule71

yystate80:
	c = l.Next()
	yyrule = 73
	l.Mark()
	goto yyrule73

yystate81:
	c = l.Next()
	yyrule = 23
	l.Mark()
	switch {
	default:
		goto yyrule23
	case c == '\n':
		goto yystate82
	case c == '\t' || c == ' ':
		goto yystate81
	}

yystate82:
	c = l.Next()
	yyrule = 23
	l.Mark()
	goto yyrule23

yystate83:
	c = l.Next()
	yyrule = 24
	l.Mark()
	goto yyrule24

yystate84:
	c = l.Next()
	yyrule = 29
	l.Mark()
	goto yyrule29

yystate85:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == '`':
		goto yystate86
	case c >= '\x01' && c <= '_' || c >= 'a' && c <= 'ÿ':
		goto yystate85
	}

yystate86:
	c = l.Next()
	yyrule = 70
	l.Mark()
	goto yyrule70

yystate87:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'r':
		goto yystate88
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate88:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'e':
		goto yystate89
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate89:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'a':
		goto yystate90
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate90:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'k':
		goto yystate91
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'j' || c >= 'l' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate91:
	c = l.Next()
	yyrule = 45
	l.Mark()
	switch {
	default:
		goto yyrule45
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate92:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'a':
		goto yystate93
	case c == 'o':
		goto yystate96
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate93:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 's':
		goto yystate94
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate94:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'e':
		goto yystate95
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate95:
	c = l.Next()
	yyrule = 60
	l.Mark()
	switch {
	default:
		goto yyrule60
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate96:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'n':
		goto yystate97
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate97:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 't':
		goto yystate98
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate98:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'i':
		goto yystate99
	case c == 'r':
		goto yystate103
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate99:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'n':
		goto yystate100
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate100:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'u':
		goto yystate101
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate101:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'e':
		goto yystate102
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate102:
	c = l.Next()
	yyrule = 46
	l.Mark()
	switch {
	default:
		goto yyrule46
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate103:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'a':
		goto yystate104
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate104:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'c':
		goto yystate105
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c == 'a' || c == 'b' || c >= 'd' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate105:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 't':
		goto yystate106
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate106:
	c = l.Next()
	yyrule = 48
	l.Mark()
	switch {
	default:
		goto yyrule48
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate107:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'a':
		goto yystate108
	case c == 'e':
		goto yystate111
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate108:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 't':
		goto yystate109
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate109:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'a':
		goto yystate110
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate110:
	c = l.Next()
	yyrule = 47
	l.Mark()
	switch {
	default:
		goto yyrule47
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate111:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'f':
		goto yystate112
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'e' || c >= 'g' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate112:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'a':
		goto yystate113
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate113:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'u':
		goto yystate114
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate114:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'l':
		goto yystate115
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate115:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 't':
		goto yystate116
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate116:
	c = l.Next()
	yyrule = 62
	l.Mark()
	switch {
	default:
		goto yyrule62
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate117:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'l':
		goto yystate118
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate118:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'i':
		goto yystate119
	case c == 's':
		goto yystate121
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate119:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'f':
		goto yystate120
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'e' || c >= 'g' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate120:
	c = l.Next()
	yyrule = 51
	l.Mark()
	switch {
	default:
		goto yyrule51
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate121:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'e':
		goto yystate122
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate122:
	c = l.Next()
	yyrule = 52
	l.Mark()
	switch {
	default:
		goto yyrule52
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate123:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'a':
		goto yystate124
	case c == 'o':
		goto yystate128
	case c == 'u':
		goto yystate130
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'n' || c >= 'p' && c <= 't' || c >= 'v' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate124:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'l':
		goto yystate125
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate125:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 's':
		goto yystate126
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate126:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'e':
		goto yystate127
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate127:
	c = l.Next()
	yyrule = 55
	l.Mark()
	switch {
	default:
		goto yyrule55
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate128:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'r':
		goto yystate129
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate129:
	c = l.Next()
	yyrule = 57
	l.Mark()
	switch {
	default:
		goto yyrule57
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate130:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'n':
		goto yystate131
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate131:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'c':
		goto yystate132
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c == 'a' || c == 'b' || c >= 'd' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate132:
	c = l.Next()
	yyrule = 56
	l.Mark()
	switch {
	default:
		goto yyrule56
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate133:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'f':
		goto yystate134
	case c == 'n':
		goto yystate135
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'e' || c >= 'g' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate134:
	c = l.Next()
	yyrule = 50
	l.Mark()
	switch {
	default:
		goto yyrule50
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate135:
	c = l.Next()
	yyrule = 58
	l.Mark()
	switch {
	default:
		goto yyrule58
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate136:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'e':
		goto yystate137
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate137:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'a':
		goto yystate138
	case c == 't':
		goto yystate140
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate138:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'd':
		goto yystate139
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate139:
	c = l.Next()
	yyrule = 61
	l.Mark()
	switch {
	default:
		goto yyrule61
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate140:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'u':
		goto yystate141
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate141:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'r':
		goto yystate142
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate142:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'n':
		goto yystate143
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate143:
	c = l.Next()
	yyrule = 53
	l.Mark()
	switch {
	default:
		goto yyrule53
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate144:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'w':
		goto yystate145
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'v' || c >= 'x' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate145:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'i':
		goto yystate146
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate146:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 't':
		goto yystate147
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate147:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'c':
		goto yystate148
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c == 'a' || c == 'b' || c >= 'd' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate148:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'h':
		goto yystate149
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'g' || c >= 'i' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate149:
	c = l.Next()
	yyrule = 59
	l.Mark()
	switch {
	default:
		goto yyrule59
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate150:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'r':
		goto yystate151
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate151:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'u':
		goto yystate152
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate152:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'e':
		goto yystate153
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate153:
	c = l.Next()
	yyrule = 54
	l.Mark()
	switch {
	default:
		goto yyrule54
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate154:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'a':
		goto yystate155
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate155:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'r':
		goto yystate156
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate156:
	c = l.Next()
	yyrule = 63
	l.Mark()
	switch {
	default:
		goto yyrule63
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate157:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'h':
		goto yystate158
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'g' || c >= 'i' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate158:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'i':
		goto yystate159
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate159:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'l':
		goto yystate160
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate160:
	c = l.Next()
	yyrule = 67
	l.Mark()
	switch {
	default:
		goto yyrule67
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c == 'e':
		goto yystate161
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate161:
	c = l.Next()
	yyrule = 49
	l.Mark()
	switch {
	default:
		goto yyrule49
	case c == '(':
		goto yystate79
	case c == '[':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate78
	}

yystate162:
	c = l.Next()
	yyrule = 21
	l.Mark()
	switch {
	default:
		goto yyrule21
	case c == '\n':
		goto yystate163
	case c == '\t' || c == ' ':
		goto yystate162
	}

yystate163:
	c = l.Next()
	yyrule = 21
	l.Mark()
	goto yyrule21

yystate164:
	c = l.Next()
	yyrule = 28
	l.Mark()
	switch {
	default:
		goto yyrule28
	case c == '|':
		goto yystate165
	}

yystate165:
	c = l.Next()
	yyrule = 26
	l.Mark()
	goto yyrule26

yystate166:
	c = l.Next()
	yyrule = 22
	l.Mark()
	goto yyrule22

yyrule1: // [ \t\r ]+
	{
		// ignore all whitespace
		goto yystate0
	}
yyrule2: // \/\*(.|\n)*\*\/
	{
		// ignore comments
		goto yystate0
	}
yyrule3: // \/\/(.)*\n
	{
		return l.char(NEWLINE)
	}
yyrule4: // \+=
	{
		return l.char(ADD_ASSIGN)
	}
yyrule5: // -=
	{
		return l.char(SUB_ASSIGN)
	}
yyrule6: // \*=
	{
		return l.char(MUL_ASSIGN)
	}
yyrule7: // \/=
	{
		return l.char(DIV_ASSIGN)
	}
yyrule8: // %=
	{
		return l.char(MOD_ASSIGN)
	}
yyrule9: // =
	{
		return l.char(ASSIGN)
	}
yyrule10: // \n
	{
		return l.char(NEWLINE)
	}
yyrule11: // ;
	{
		return l.char(NEWLINE)
	}
yyrule12: // ,[ \t\r]*\n?
	{
		return l.char(COMMA)
	}
yyrule13: // :
	{
		return l.char(COLON)
	}
yyrule14: // \.\.
	{
		return l.char(DOUBLEDOT)
	}
yyrule15: // \.
	{
		return l.char(DOT)
	}
yyrule16: // \?
	{
		return l.char(QUESTION)
	}
yyrule17: // \([ \t]*\n?
	{
		return l.char(LPAREN)
	}
yyrule18: // \n[ \t]*\)
	{
		return l.char(RPAREN)
	}
yyrule19: // \)
	{
		return l.char(RPAREN)
	}
yyrule20: // @\{[ \t]*\n?
	{
		return l.char(OBJ)
	}
yyrule21: // \{[ \t]*\n?
	{
		return l.char(LBRACE)
	}
yyrule22: // \}
	{
		return l.char(RBRACE)
	}
yyrule23: // \[[ \t]*\n?
	{
		return l.char(LBRACKET)
	}
yyrule24: // \]
	{
		return l.char(RBRACKET)
	}
yyrule25: // &&
	{
		return l.char(AND)
	}
yyrule26: // \|\|
	{
		return l.char(OR)
	}
yyrule27: // \&
	{
		return l.char(BIT_AND)
	}
yyrule28: // \|
	{
		return l.char(BIT_OR)
	}
yyrule29: // \^
	{
		return l.char(BIT_XOR)
	}
yyrule30: // \<\<
	{
		return l.char(LEFT_SHIFT)
	}
yyrule31: // \>\>
	{
		return l.char(RIGHT_SHIFT)
	}
yyrule32: // \*\*
	{
		return l.char(POW)
	}
yyrule33: // \+[ \t\r]*\n?
	{
		return l.char(ADD)
	}
yyrule34: // -[ \t\r]*\n?
	{
		return l.char(SUB)
	}
yyrule35: // \*[ \t\r]*\n?
	{
		return l.char(MUL)
	}
yyrule36: // \/[ \t\r]*\n?
	{
		return l.char(DIV)
	}
yyrule37: // %[ \t\r]*\n?
	{
		return l.char(MOD)
	}
yyrule38: // ==[ \t\r]*\n?
	{
		return l.char(EQ)
	}
yyrule39: // !=[ \t\r]*\n?
	{
		return l.char(NOT_EQ)
	}
yyrule40: // !
	{
		return l.char(NOT)
	}
yyrule41: // \<=[ \t\r]*\n?
	{
		return l.char(LTE)
	}
yyrule42: // >=[ \t\r]*\n?
	{
		return l.char(GTE)
	}
yyrule43: // \<[ \t\r]*\n?
	{
		return l.char(LT)
	}
yyrule44: // >[ \t\r]*\n?
	{
		return l.char(GT)
	}
yyrule45: // break
	{
		return l.char(BREAK)
	}
yyrule46: // continue
	{
		return l.char(CONTINUE)
	}
yyrule47: // data
	{
		return l.char(DATA)
	}
yyrule48: // contract
	{
		return l.char(CONTRACT)
	}
yyrule49: // while
	{
		return l.char(WHILE)
	}
yyrule50: // if
	{
		return l.char(IF)
	}
yyrule51: // elif
	{
		return l.char(ELIF)
	}
yyrule52: // else
	{
		return l.char(ELSE)
	}
yyrule53: // return
	{
		return l.char(RETURN)
	}
yyrule54: // true
	{
		return l.char(TRUE)
	}
yyrule55: // false
	{
		return l.char(FALSE)
	}
yyrule56: // func
	{
		return l.char(FUNC)
	}
yyrule57: // for
	{
		return l.char(FOR)
	}
yyrule58: // in
	{
		return l.char(IN)
	}
yyrule59: // switch
	{
		return l.char(SWITCH)
	}
yyrule60: // case
	{
		return l.char(CASE)
	}
yyrule61: // read
	{
		return l.char(READ)
	}
yyrule62: // default
	{
		return l.char(DEFAULT)
	}
yyrule63: // var
	{
		return l.char(VAR)
	}
yyrule64: // {float}
	{
		{
			ai, _ := strconv.ParseFloat(string(l.TokenBytes(nil)), 64)
			lval.f = ai
			return l.char(FLOAT)
		}
		goto yystate0
	}
yyrule65: // {hexint}
	{
		{
			val, _ := strconv.ParseInt(string(l.TokenBytes(nil)), 0, 64)
			lval.i = int64(val)
			return l.char(INT)
		}
		goto yystate0
	}
yyrule66: // {int}
	{
		{
			ai, _ := strconv.Atoi(string(l.TokenBytes(nil)))
			lval.i = int64(ai)
			return l.char(INT)
		}
		goto yystate0
	}
yyrule67: // {identifier}
	{
		{
			lval.s = string(l.TokenBytes(nil))
			return l.char(IDENT)
		}
		goto yystate0
	}
yyrule68: // {env}
	{
		{
			lval.s = string(l.TokenBytes(nil))
			lval.s = lval.s[1:]
			return l.char(ENV)
		}
		goto yystate0
	}
yyrule69: // {string}
	{
		{
			var err error
			s := strings.Replace(string(l.TokenBytes(nil)), "\n", `\n`, -1)
			lval.s, err = strconv.Unquote(`"` + s[1:len(s)-1] + `"`)
			if err != nil {
				l.Error(err.Error())
			}
			return l.char(STRING)
		}
		goto yystate0
	}
yyrule70: // {qstring}
	{
		{
			s := string(l.TokenBytes(nil))
			lval.s = s[1 : len(s)-1]
			return l.char(STRING)
		}
		goto yystate0
	}
yyrule71: // {call}
	{
		{
			lval.s = string(l.TokenBytes(nil))
			lval.s = lval.s[:len(lval.s)-1]
			return l.char(CALL)
		}
		goto yystate0
	}
yyrule72: // {callcontract}
	{
		{
			lval.s = string(l.TokenBytes(nil))
			lval.s = lval.s[:len(lval.s)-1]
			return l.char(CALLCONTRACT)
		}
		goto yystate0
	}
yyrule73: // {index}
	{
		{
			lval.s = string(l.TokenBytes(nil))
			lval.s = lval.s[:len(lval.s)-1]
			return l.char(INDEX)
		}
		goto yystate0
	}
	panic("unreachable")

	goto yyabort // silence unused label error

yyabort: // no lexem recognized
	if c, ok := l.Abort(); ok {
		return l.char(c)
	}

	goto yyAction
}
